#!/bin/sh

set -e
echo "=> Installing Power-Button support\n"

sudo cp shutdown-button.py /usr/local/bin/
sudo chmod +x /usr/local/bin/shutdown-button.py
sudo cp shutdown-button.service /etc/systemd/system/
sudo systemctl enable shutdown-button.service
sudo systemctl start shutdown-button.service

echo "Support for shutdown button activated.\n"
