#!/bin/sh

set -e

echo "=> Installing Power-Button support\n"

sudo cp shutdown-button.py /usr/local/bin
sudo chmod +x /usr/local/bin/shutdown-button.py
sudo cp shutdown-button.service /etc/systemd/system
sudo systemctl enable shutdown_button.service
sudo systemctl start shutdown_button.service

echo "Support for shutdown button installed.\n"
