#! /bin/sh

set -e

echo "=> Deactivating shutdown-button script...\n"
sudo update-rc.d shutdown-button.sh remove
sudo /etc/init.d/shutdown-button.sh stop

echo "=> Removing shutdown-button script...\n"
sudo rm -rf /usr/local/bin/shutdown-button.py 
sudo rm -rf /etc/init.d/shutdown-button.sh 

echo "Shutdown-button script.\n"
